# Generated by Django 6.0.6 on 2026-09-28 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='What customers type. Stored in capitals; matched without regard to case.', max_length=30, unique=True)),
                ('percent_off', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('scope', models.CharField(choices=[('ORDER', 'Whole order'), ('PRODUCTS', 'Specific products')], default='ORDER', max_length=8)),
                ('starts_on', models.DateField(help_text='First day the code works.')),
                ('ends_on', models.DateField(help_text='Last day the code works (inclusive).')),
                ('is_active', models.BooleanField(default=True, help_text='Off means retired — the code stops working.')),
                ('products', models.ManyToManyField(blank=True, help_text='Only for product coupons — the products the discount applies to.', related_name='coupons', to='products.product')),
            ],
            options={
                'ordering': ['-starts_on', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='coupon_ends_after_it_starts'), models.CheckConstraint(condition=models.Q(('percent_off__gte', 1), ('percent_off__lte', 100)), name='coupon_percent_between_1_and_100')],
            },
        ),
    ]
